### ISSUE TITLE
Errors when loading the .vimrc on macOS

### ISSUE THREAD

**Issue by tfiala** [thoughtstream/Damian-Conway-s-Vim-Setup#12]
Hi, Dr. Conway!

I was just trying to go through your O'Reilly vim videos with your setup.  When I use this repo as my .vim and .vimrc, there seems to be a few files it is expecting to find that aren't in the repo:

```shell
$ vim
Error detected while processing /Users/tfiala/.vimrc:
line  623:
E484: Can't open file /Users/tfiala/.vim/perlmodules
Error detected while processing function <SNR>20_recompile_spelling_files:
line    2:
E484: Can't open file /Users/damian/.vim/grammarian/errors/spell/en.latin1.add
line    5:
E484: Can't open file /Users/damian/.vim/grammarian/cautions/spell/en.latin1.add
Press ENTER or type command to continue
```

Is there any chance you might be able to add those?  Is there any major harm if those aren't around?  (I figure the missing Perl dir might significantly reduce functionality).

Thanks!

**Comment by thoughtstream** [comment]
Hi Todd,

Thanks for your interest in my Vim videos and my .vimrc

> E484: Can't open file /Users/tfiala/.vim/perlmodules

This is a plaintext file with a list of Perl modules I have installed,
one per line. It allows my smartcom.vim configuration to tab-complete on
'use' statements in Perl files. You could add your own file with a list
of your own modules if you wanted. Its absence will have no adverse
effect apart from not supporting tab-complete on 'use' statements in
Perl files. ;-)


> Error detected while processing function <SNR>20_recompile_spelling_files:
> line    2:
> E484: Can't open file
/Users/damian/.vim/grammarian/errors/spell/en.latin1.add
> line    5:
> E484: Can't open file
/Users/damian/.vim/grammarian/cautions/spell/en.latin1.add

These need to be set up by downloading and installing the
Lingua::EN::Grammarian Perl module from CPAN. Then running
bin/setup_vim_plugin from that distribution's root directory.
Without them, the only effect will be to disable the grammarian
grammar checking within Vim.

All the best,

Damian

**Comment by tfiala** [comment]
> You could add your own file with a list of your own modules if you wanted.

Ah I see.

> These need to be set up by downloading and installing the Lingua::EN::Grammarian Perl module from CPAN. Then running bin/setup_vim_plugin from that distribution's root directory.

Oh okay.

Thank you so much, and thanks for putting your vimrc setup online!

Sincerely,
Todd Fiala
