### ISSUE TITLE
next match error when searching in split files

### ISSUE THREAD

**Issue by cwong47** [thoughtstream/Damian-Conway-s-Vim-Setup#14]
i have 2 files in split mode. the matching works well on the first file. when i switch over to the 2nd file and search next (n), i get the following error -
```
Error detected while processing function HLNext[2]..HLNextOff:
line    2:
E803: ID not found: 14
Press ENTER or type command to continue
```

**Comment by thoughtstream** [comment]
Should be fixed in the latest snapshot.
