### ISSUE TITLE
Array Out of Bounds Error - yankmatch

### ISSUE THREAD

**Issue by hallzy** [thoughtstream/Damian-Conway-s-Vim-Setup#18]
This line appears to produce an array out of bounds error when a visual selection is made which does not start on the first line of a file.

https://github.com/thoughtstream/Damian-Conway-s-Vim-Setup/blob/357682682ae8c41925298f63985a0f0b9b89b61c/plugin/yankmatches.vim#L65

The following code should resolve that:

```vimscript
call remove(lnverted_line_nums, line_num-start_line)
```

The plugin can also be made to respect a user's `clipboard` setting by replacing

```vimscript
let @" = yanked
```

with 

```vimpscript
    if !exists('g:YankMatches#ClipboardRegister')
        let l:clipboard_flags = split(&clipboard, ',')
        if index(l:clipboard_flags, 'unnamedplus') >= 0
            let g:YankMatches#ClipboardRegister='+'
        elseif index(l:clipboard_flags, 'unnamed') >= 0
            let g:YankMatches#ClipboardRegister='*'
        else
            let g:YankMatches#ClipboardRegister='"'
        endif
    endif
    let l:command = ':let @' . g:YankMatches#ClipboardRegister . ' = yanked'
    execute 'normal! ' . l:command . "\<cr>"
```

while also allowing the user to specify if they want a different register.

**Comment by thoughtstream** [comment]
Thanks, Steven.

I'm grateful for the bug-fix and the patch to honour clipboard
preferences.

Much appreciated!

Damian

**Comment by bean5** [comment]
So is this open or closed, @thoughtstream ?

**Comment by thoughtstream** [comment]
Closed. Thanks.

Damian
