### ISSUE TITLE
Any chance these plugins could be organized into separate repos?

### ISSUE THREAD

**Issue by fent** [thoughtstream/Damian-Conway-s-Vim-Setup#19]
Hello,

I copied a couple of your plugins to my `~/.vim/plugin` directory, thank you. But nowadays, it's much more common to install vim plugins using plugin managers (such as [vundle](https://github.com/VundleVim/Vundle.vim) and [vim-plug](https://github.com/junegunn/vim-plug)) that download and install plugins from repos.

Again, it's not a big deal for someone to manually install one plugin one one machine, but using a plugin manager nowadays makes things super convenient by making plugin installation across several machines much easier. And then later updating them.

**Comment by thoughtstream** [comment]
Thanks for taking the time to suggest this.

And, if someone wants to fork this repo and rearrange it that way,
I certainly have no objection.

However, I won't be doing so myself. I have absolutely no
intention of getting into the Vim plugin business.
When I wrote "Totally unsupported", I really meant it. ;-)

All the best,

Damian
