### ISSUE TITLE
Code::Refactor missing

### ISSUE THREAD

**Issue by Sadrak** [thoughtstream/Damian-Conway-s-Vim-Setup#22]
from the perlrefactor.vim there is a systemcall with a Module called Code::Refactor which is curently not public available.Perhaps this can be added here? Or published at cpan?

**Comment by thoughtstream** [comment]
Thanks for taking the time to report the omission, Felix.

The Code::Refactor module will be released at the TPCiA conference in
Amsterdam next year.

All the best,

Damian
